'''This file contains the definitions of the constants used in scoring a given
play.  It will be imported directly into the namespace of play_finder_wwf.'''

WORD_LIST = dict([(i, set()) for i in range(2, 16)])
with open('word_list_wwf.txt') as wwf_file:
    for line in wwf_file:
        word=line.strip()
        WORD_LIST[len(word)].add(word)

WORD_SCORE_MULTIPLIER = {}
WORD_SCORE_MULTIPLIER[(0, 3)] = WORD_SCORE_MULTIPLIER[(0, 11)] = 3
WORD_SCORE_MULTIPLIER[(3, 0)] = WORD_SCORE_MULTIPLIER[(3, 14)] = 3
WORD_SCORE_MULTIPLIER[(11, 0)] = WORD_SCORE_MULTIPLIER[(11, 14)] = 3
WORD_SCORE_MULTIPLIER[(14, 3)] = WORD_SCORE_MULTIPLIER[(14, 11)] = 3
WORD_SCORE_MULTIPLIER[(1, 5)] = WORD_SCORE_MULTIPLIER[(1, 9)] = 2
WORD_SCORE_MULTIPLIER[(5, 1)] = WORD_SCORE_MULTIPLIER[(5, 13)] = 2
WORD_SCORE_MULTIPLIER[(7, 3)] = WORD_SCORE_MULTIPLIER[(7, 11)] = 2
WORD_SCORE_MULTIPLIER[(9, 1)] = WORD_SCORE_MULTIPLIER[(9, 13)] = 2
WORD_SCORE_MULTIPLIER[(13, 5)] = WORD_SCORE_MULTIPLIER[(13, 9)] = 2
WORD_SCORE_MULTIPLIER[(3, 7)] = WORD_SCORE_MULTIPLIER[(11, 7)] = 2

LETTER_SCORE_MULTIPLIER = {}
LETTER_SCORE_MULTIPLIER[(0, 6)] = LETTER_SCORE_MULTIPLIER[(0, 8)] = 3
LETTER_SCORE_MULTIPLIER[(3, 3)] = LETTER_SCORE_MULTIPLIER[(3, 11)] = 3
LETTER_SCORE_MULTIPLIER[(5, 5)] = LETTER_SCORE_MULTIPLIER[(5, 9)] = 3
LETTER_SCORE_MULTIPLIER[(6, 0)] = LETTER_SCORE_MULTIPLIER[(6, 14)] = 3
LETTER_SCORE_MULTIPLIER[(8, 0)] = LETTER_SCORE_MULTIPLIER[(8, 14)] = 3
LETTER_SCORE_MULTIPLIER[(9, 5)] = LETTER_SCORE_MULTIPLIER[(9, 9)] = 3
LETTER_SCORE_MULTIPLIER[(11, 3)] = LETTER_SCORE_MULTIPLIER[(11, 11)] = 3
LETTER_SCORE_MULTIPLIER[(14, 6)] = LETTER_SCORE_MULTIPLIER[(14, 8)] = 3
LETTER_SCORE_MULTIPLIER[(1, 2)] = LETTER_SCORE_MULTIPLIER[(1, 12)] = 2
LETTER_SCORE_MULTIPLIER[(2, 1)] = LETTER_SCORE_MULTIPLIER[(2, 4)] = 2
LETTER_SCORE_MULTIPLIER[(2, 10)] = LETTER_SCORE_MULTIPLIER[(2, 13)] = 2
LETTER_SCORE_MULTIPLIER[(4, 2)] = LETTER_SCORE_MULTIPLIER[(4, 6)] = 2
LETTER_SCORE_MULTIPLIER[(4, 8)] = LETTER_SCORE_MULTIPLIER[(4, 12)] = 2
LETTER_SCORE_MULTIPLIER[(6, 4)] = LETTER_SCORE_MULTIPLIER[(6, 10)] = 2
LETTER_SCORE_MULTIPLIER[(8, 4)] = LETTER_SCORE_MULTIPLIER[(8, 10)] = 2
LETTER_SCORE_MULTIPLIER[(10, 2)] = LETTER_SCORE_MULTIPLIER[(10, 6)] = 2
LETTER_SCORE_MULTIPLIER[(10, 8)] = LETTER_SCORE_MULTIPLIER[(10, 12)] = 2
LETTER_SCORE_MULTIPLIER[(12, 1)] = LETTER_SCORE_MULTIPLIER[(12, 4)] = 2
LETTER_SCORE_MULTIPLIER[(12, 10)] = LETTER_SCORE_MULTIPLIER[(12, 13)] = 2
LETTER_SCORE_MULTIPLIER[(13, 2)] = LETTER_SCORE_MULTIPLIER[(13, 12)] = 2

TILE_VALUES = {}
TILE_VALUES['a'] = TILE_VALUES['e'] = 1
TILE_VALUES['i'] = TILE_VALUES['o'] = 1
TILE_VALUES['r'] = TILE_VALUES['s'] = 1
TILE_VALUES['t'] = 1
TILE_VALUES['d'] = TILE_VALUES['l'] = 2
TILE_VALUES['n'] = TILE_VALUES['u'] = 2
TILE_VALUES['g'] = TILE_VALUES['h'] = 3
TILE_VALUES['y'] = 3
TILE_VALUES['b'] = TILE_VALUES['c'] = 4
TILE_VALUES['f'] = TILE_VALUES['m'] = 4
TILE_VALUES['p'] = TILE_VALUES['w'] = 4
TILE_VALUES['k'] = TILE_VALUES['v'] = 5
TILE_VALUES['x'] = 8
TILE_VALUES['j'] = TILE_VALUES['q'] = 10
TILE_VALUES['z'] = 10
